name: ✨ Feature Request
description: Suggest an idea or enhancement for any part of UNaIVERSE.
title: "[FEAT]: "
labels: ["enhancement", "needs-discussion"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Which part of UNaIVERSE does this feature request relate to?
      options:
        - Python Library
        - Web App / Portal
        - A new type of 'World' or 'Agent' behavior
        - Documentation
        - Other (please specify below)
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem?
      description: "A clear and concise description of what the problem is. Ex. 'I find it difficult to...'"
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Describe the solution you'd like
      description: "How would this new feature work? Be as detailed as you can."
    validations:
      required: true

  - type: textarea
    id: vision-alignment
    attributes:
      label: How does this align with the UNaIVERSE vision?
      description: "Please explain how your suggestion supports the core principles of UNaIVERSE (Privacy, Low Energy, Decentralization)."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Add any other context, mockups, or links to relevant research here."

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our project's Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
